variables:
  GIT_STRATEGY: clone

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: maven:3.8.5-openjdk-18
  tags:
    - dalfcs_docker_autoscale
  script:
    - mvn clean compile
test-job:
  stage: test
  image: maven:3.8.5-openjdk-18
  tags:
    - dalfcs_docker_autoscale
  script:
    - mvn test


deploy-test-job:
  stage: deploy
  image: ruby:latest
  tags:
    - dalfcs_docker_autoscale
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$APPLICATION_TEST --api-key=$API_KEY_TEST
  only:
    - release

deploy-production-job:
  stage: deploy
  image: ruby:latest
  tags:
    - dalfcs_docker_autoscale
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$APPLICATION_PRODUCTION --api-key=$API_KEY_PRODUCTION
  only:
    - main

